/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.bccontrolpanel.dataservice.controller;

import com.bccontrolpanel.dataservice.DataService;
import com.bccontrolpanel.dataservice.DataService.Struct;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/data")
public class DataController {

    @Autowired
    private DataService dataService;

    @RequestMapping(value = "/lol", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Struct[] lol() {
        return dataService.lol();
    }
}
