/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.bccontrolpanel.mailservice.controller;

import com.bccontrolpanel.mailservice.MailService;
import com.bccontrolpanel.bcdata.Users;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/mail")
public class MailController {

    @Autowired
    private MailService mailService;

    @RequestMapping(value = "/sendPasswordReset", produces = "application/json", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String sendPasswordReset(@RequestParam(value = "userID", required = false) int userID) {
        return mailService.sendPasswordReset(userID);
    }

    @RequestMapping(value = "/userByID", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Users getUserByID(@RequestParam(value = "usrID", required = false) int usrID) {
        return mailService.getUserByID(usrID);
    }
}
