/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.bccontrolpanel.simonservice.controller;
import com.bccontrolpanel.simonservice.SimonService;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController	
@RequestMapping(value = "/simon")
public class SimonController{

	@Autowired	
	private SimonService simonservice;

	@RequestMapping(value = "/sampleJavaOperation" ,  produces = "application/json", method = RequestMethod.GET )
	public String sampleJavaOperation(@RequestParam(value="name", required=false)String name )   {
        
            return simonservice.sampleJavaOperation(name);
	}
} 