/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.bccontrolpanel.contextservice.controller;

import com.bccontrolpanel.contextservice.ContextService;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/context")
public class ContextController {

    @Autowired
    private ContextService contextService;

    @RequestMapping(value = "/contextFileID", produces = "application/json", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String getContextFileID(@RequestParam(value = "FileName", required = false) String FileName) {
        return contextService.getContextFileID(FileName);
    }

    @RequestMapping(value = "/contextFiles", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String[] listContextFiles() {
        return contextService.listContextFiles();
    }

    @RequestMapping(value = "/countContextFiles", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public long countContextFiles() {
        return contextService.countContextFiles();
    }
}
