/*Copyright (c) 2016-2017 Business on Demand Ltd. All Rights Reserved. This software is the confidential and proprietary information of Business on Demand Ltd. You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Business on Demand Ltd.*/

package com.bccontrolpanel.bcdata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * ContextparameterId generated by hbm2java
 */
@Embeddable
public class ContextparameterId  implements java.io.Serializable {

    private String contextName;
    private String contextFileName;
    private String parameter;

    public ContextparameterId() {
    }


    public String getContextName() {
        return this.contextName;
    }
    
    public void setContextName(String contextName) {
        this.contextName = contextName;
    }
    public String getContextFileName() {
        return this.contextFileName;
    }
    
    public void setContextFileName(String contextFileName) {
        this.contextFileName = contextFileName;
    }
    public String getParameter() {
        return this.parameter;
    }
    
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof ContextparameterId) )
		    return false;

		 ContextparameterId that = (ContextparameterId) o;

         return ( (this.getContextName()==that.getContextName()) || ( this.getContextName()!=null && that.getContextName()!=null && this.getContextName().equals(that.getContextName()) ) )
 && ( (this.getContextFileName()==that.getContextFileName()) || ( this.getContextFileName()!=null && that.getContextFileName()!=null && this.getContextFileName().equals(that.getContextFileName()) ) )
 && ( (this.getParameter()==that.getParameter()) || ( this.getParameter()!=null && that.getParameter()!=null && this.getParameter().equals(that.getParameter()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getContextName() == null ? 0 : this.getContextName().hashCode() );
         result = 37 * result + ( getContextFileName() == null ? 0 : this.getContextFileName().hashCode() );
         result = 37 * result + ( getParameter() == null ? 0 : this.getParameter().hashCode() );

         return result;
    }


}

