/*Copyright (c) 2016-2017 Business on Demand Ltd. All Rights Reserved. This software is the confidential and proprietary information of Business on Demand Ltd. You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with Business on Demand Ltd.*/

package com.bccontrolpanel.bcdata;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Contextparameter generated by hbm2java
 */
@Entity
@Table(name="`contextparameter`"
    ,schema="bcdata"
)
@IdClass(value=ContextparameterId.class)
public class Contextparameter  implements java.io.Serializable {

    private String contextName;
    private String contextFileName;
    private String parameter;
    private String value;
    private boolean enabled;

    public Contextparameter() {
    }


    @Id 
    

    @Column(name="`ContextName`", nullable=false, insertable=false, updatable=false, length=64)
    public String getContextName() {
        return this.contextName;
    }
    
    public void setContextName(String contextName) {
        this.contextName = contextName;
    }
    @Id 
    

    @Column(name="`ContextFileName`", nullable=false, insertable=false, updatable=false)
    public String getContextFileName() {
        return this.contextFileName;
    }
    
    public void setContextFileName(String contextFileName) {
        this.contextFileName = contextFileName;
    }
    @Id 
    

    @Column(name="`Parameter`", nullable=false, insertable=false, updatable=false, length=64)
    public String getParameter() {
        return this.parameter;
    }
    
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    

    @Column(name="`Value`", length=1024)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    

    @Column(name="`Enabled`", nullable=false)
    public boolean isEnabled() {
        return this.enabled;
    }
    
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Contextparameter) )
		    return false;

		 Contextparameter that = (Contextparameter) o;

         return ( (this.getContextName()==that.getContextName()) || ( this.getContextName()!=null && that.getContextName()!=null && this.getContextName().equals(that.getContextName()) ) )
 && ( (this.getContextFileName()==that.getContextFileName()) || ( this.getContextFileName()!=null && that.getContextFileName()!=null && this.getContextFileName().equals(that.getContextFileName()) ) )
 && ( (this.getParameter()==that.getParameter()) || ( this.getParameter()!=null && that.getParameter()!=null && this.getParameter().equals(that.getParameter()) ) )
 && ( (this.getValue()==that.getValue()) || ( this.getValue()!=null && that.getValue()!=null && this.getValue().equals(that.getValue()) ) )
 && (this.isEnabled()==that.isEnabled());
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getContextName() == null ? 0 : this.getContextName().hashCode() );
         result = 37 * result + ( getContextFileName() == null ? 0 : this.getContextFileName().hashCode() );
         result = 37 * result + ( getParameter() == null ? 0 : this.getParameter().hashCode() );
         result = 37 * result + ( getValue() == null ? 0 : this.getValue().hashCode() );
         result = 37 * result + (this.isEnabled()?1:0);

         return result;
    }


}

