
package com.bccontrolpanel.bcdata.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;

import com.wavemaker.runtime.data.model.CustomQuery;
import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.exception.QueryParameterMismatchException;

@Service
public class BcdataQueryExecutorServiceImpl implements BcdataQueryExecutorService {
	private static final Logger LOGGER = LoggerFactory.getLogger(BcdataQueryExecutorServiceImpl.class);

	@Autowired
	@Qualifier("bcdataWMQueryExecutor")
	private WMQueryExecutor queryExecutor;

	@Transactional(value = "bcdataTransactionManager")
	@Override
	public Page<Object> executeQueryContextValue(Pageable pageable, java.lang.String qParameter, java.lang.String qContextFileName)
	throws QueryParameterMismatchException{
        Map<String, Object> params = new HashMap<String, Object>();
        params.put("qParameter", qParameter);
        params.put("qContextFileName", qContextFileName);
        return queryExecutor.executeNamedQuery("queryContextValue", params, pageable);
	}

	@Transactional(value = "bcdataTransactionManager")
	@Override
	public Page<Object> executeWMCustomQuerySelect(CustomQuery query, Pageable pageable) {
	    return queryExecutor.executeCustomQuery(query, pageable);
	}

	@Transactional(value = "bcdataTransactionManager")
    @Override
    public int executeWMCustomQueryUpdate(CustomQuery query) {
        return queryExecutor.executeCustomQueryForUpdate(query);
    }
}

