/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.bccontrolpanel.settingsservice.controller;

import com.bccontrolpanel.settingsservice.SettingsService;
import java.lang.String;
import java.io.IOException;
import java.util.List;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/settings")
public class SettingsController {

    @Autowired
    private SettingsService settingsservice;

    @RequestMapping(value = "/countFiles", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public int countFiles(@RequestParam(value = "relativePath", required = false) String relativePath) throws IOException {
        return settingsservice.countFiles(relativePath);
    }

    @RequestMapping(value = "/files", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public String[] listFiles(@RequestParam(value = "relativePath", required = false) String relativePath) throws IOException {
        return settingsservice.listFiles(relativePath);
    }

    @RequestMapping(value = "/openFile", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public List openFile(@RequestParam(value = "filename", required = false) String filename) throws IOException {
        return settingsservice.openFile(filename);
    }

    @RequestMapping(value = "/writeToFile", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public void writeToFile(@RequestParam(value = "filename", required = false) String filename, @RequestParam(value = "contents", required = false) String contents) throws IOException {
        settingsservice.writeToFile(filename, contents);
    }
}
