/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.bccontrolpanel.settingsservice.controller;

import com.bccontrolpanel.settingsservice.SettingsService;
import java.lang.String;
import java.io.IOException;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.*;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/settings")
public class SettingsController {

    @Autowired
    private SettingsService settingsservice;

    @RequestMapping(value = "/files", method = RequestMethod.GET)
    public int listFiles(@RequestParam(value = "relativePath", required = false) String relativePath) throws IOException {
        return settingsservice.listFiles(relativePath);
    }
}
